version: '3.5'

services:
  django:
    build: .
    container_name: django_backend
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - site:/usr/src/app
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
    ports: 
      - "80:80"
    depends_on:
      - django
  
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - site:/var/www/site
    command: certonly --webroot --webroot-path=/var/www/site --email kejte1@mail.ru --agree-tos --no-eff-email -d plush-toy.shop
      
volumes:
  pgdata:
    name: pgdata
    
  static: 
    name: static
  
  media:
    name: media
  
  site:
    name: site
  
  etc-letsencrypt:
    name: letsencrypt