version: '3.5'

services:
  django:
    build: .
    container_name: django_backend
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - static:/usr/src/app/static
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=darianatoys
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
      
volumes:

  static: 
    name: static
