
version: '3.5'

services:
  django:
    build: .
    container_name: django_backend
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - site:/usr/src/app
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  nginx:
    build: ./nginx
    volumes:
      - static:/static
      - media:/media
      - etc-letsencrypt:/etc/letsencrypt
    ports: 
      - "443:443"
      - "80:80"
    depends_on:
      certbot:
        condition: service_completed_successfully
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
    command: certonly --standalone --non-interactive
                      --agree-tos --email l0nelyleob.working@gmail.com
                      -d plush-toy.shop
      
volumes:
  pgdata:
    name: pgdata
    
  static: 
    name: static
  
  media:
    name: media
  
  site:
    name: site
  
  etc-letsencrypt:
    name: letsencrypt
