# Generated by Django 4.2.2 on 2023-06-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_toy_time_update_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='time_create',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', verbose_name='Ярлык для URL'),
        ),
        migrations.AddField(
            model_name='toy',
            name='photo',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='toy',
            name='slug',
            field=models.SlugField(default='', verbose_name='Ярлык для URL'),
        ),
    ]
