# Generated by Django 4.2.2 on 2023-06-27 20:11

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_toy_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='photo',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to=store.models.upload_to_toys, verbose_name='Фото игрушки')),
                ('toy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='store.toy', verbose_name='Связь к игрушке')),
            ],
            options={
                'verbose_name': 'Аватар',
                'verbose_name_plural': 'Аватары',
            },
        ),
    ]
