# Generated by Django 4.2.2 on 2023-06-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_toy_photo_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='avatar',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='toy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='store.toy', verbose_name='Связь к игрушке'),
        ),
    ]
