# Generated by Django 4.2.2 on 2023-07-01 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_rename_avatar_avatar_photo_alter_avatar_toy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория игрушек', 'verbose_name_plural': 'Категории игрушек'},
        ),
        migrations.AlterModelOptions(
            name='toy',
            options={'ordering': ['is_published', 'category'], 'verbose_name': 'Игрушка', 'verbose_name_plural': 'Игрушки'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NW', 'Новый'), ('IN', 'В обработке'), ('RD', 'Готов')], default='NW', max_length=2, verbose_name='Статус заказа')),
                ('items', models.ManyToManyField(related_name='transaction', to='store.cartitem', verbose_name='Игрушки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.toy', verbose_name='Игрушка'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='cart', to='store.cartitem', verbose_name='Игрушки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
    ]
