# Generated by Django 4.2.1 on 2023-07-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_cartitem_alter_category_options_alter_toy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(null=True, related_name='cart', to='store.cartitem', verbose_name='Игрушки'),
        ),
    ]
