# Generated by Django 4.2.1 on 2023-07-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='cart', to='store.cartitem', verbose_name='Игрушки'),
        ),
    ]
