# Generated by Django 4.2.1 on 2023-07-06 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0009_alter_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Заголовок отзыва')),
                ('description', models.CharField(max_length=500, verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5)], default='Five', verbose_name='Рейтинг')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.toy', verbose_name='Игрушка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
            ],
        ),
    ]
