# Generated by Django 4.2.1 on 2023-07-06 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='toy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.toy', verbose_name='Связь с игрушкой'),
        ),
    ]
