# Generated by Django 4.2.1 on 2023-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_review_toy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='toy',
        ),
        migrations.AddField(
            model_name='toy',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='store.review', verbose_name='Отзывы об игрушке'),
        ),
    ]
