# Generated by Django 4.2.1 on 2023-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('NW', 'Новое'), ('IN', 'В обработке'), ('RD', 'Готово')], default='NW', max_length=2, verbose_name='Статус обращения'),
        ),
    ]
