# Generated by Django 4.2.1 on 2023-07-11 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transactions',
            field=models.ManyToManyField(to='store.transaction', verbose_name='Заказы'),
        ),
    ]
